// This file was generated by dart_openapi_model_gen
class CompanyModules {
  static const modelName = "company_modules";

  final int id;
  final String createdAt;
  final int companyId;
  final int moduleId;
  final double priceCharged;

  CompanyModules({required  this.id, required  this.createdAt, required  this.companyId, required  this.moduleId, required  this.priceCharged, });

  CompanyModules copyWith({
    int? id,
    String? createdAt,
    int? companyId,
    int? moduleId,
    double? priceCharged,
  }) => CompanyModules(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        companyId: companyId ?? this.companyId, 
        moduleId: moduleId ?? this.moduleId, 
        priceCharged: priceCharged ?? this.priceCharged, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'company_id': companyId,
        'module_id': moduleId,
        'price_charged': priceCharged,
  };

  factory CompanyModules.fromJson(Map<String, dynamic> json) => CompanyModules(
        id: json['id'] as int,
        createdAt: json['created_at'] as String,
        companyId: json['company_id'] as int,
        moduleId: json['module_id'] as int,
        priceCharged: json['price_charged'].toDouble(),
  );
}
