// This file was generated by dart_openapi_model_gen
class Company {
  static const modelName = "company";

  final int id;
  final String name;
  final String createdAt;
  final String ownerId;

  Company({required  this.id, required  this.name, required  this.createdAt, required  this.ownerId, });

  Company copyWith({
    int? id,
    String? name,
    String? createdAt,
    String? ownerId,
  }) => Company(
        id: id ?? this.id, 
        name: name ?? this.name, 
        createdAt: createdAt ?? this.createdAt, 
        ownerId: ownerId ?? this.ownerId, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'created_at': createdAt,
        'owner_id': ownerId,
  };

  factory Company.fromJson(Map<String, dynamic> json) => Company(
        id: json['id'] as int,
        name: json['name'] as String,
        createdAt: json['created_at'] as String,
        ownerId: json['owner_id'] as String,
  );
}
